#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: "Ahmad Mostafa's Resume"
url: 'http://webjeda.com'
baseurl: '/' #change it according to your repository name
description: "Ahmad Mostafa's Resume"
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: "turquoise"
chrome_mobile_color: "#008080"

# Tracker
analytics: UA-83979019-1



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
